# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shuup', '0057_remove_product_stock_behavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shuup.Order')),
            ],
        ),
    ]
