# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataorder',
            name='latitue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dataorder',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
