# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_data', '0002_auto_20190317_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataorder',
            old_name='latitue',
            new_name='latitude',
        ),
    ]
